#install: skip

language: c

#compiler:
#        - gcc
#        - clang

os:
        - linux
        - osx
        - freebsd

branches:
#        - master
        - dev

script: touch configure aclocal.m4 Makefile.in src/Makefile.in doc/Makefile.in config.h.in &&
        ./configure --enable-public-interface &&
        sleep 1 &&
        touch doc/libnetblock.info &&
        sleep 1 &&
        cat src/lnb_cfg.h.in &&
        make

